test_non_linear_solvers – Numerical Methods
test_non_linear_solvers Program
31 statements
Source File
Uses
non_linear_solvers
program to test the non_linear_solvers module
Calls
Contents
Functions
f df f_vec J
Functions
function f(x) result(y)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x
Return Value real
function df(x) result(y)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x
Return Value real
function f_vec(x) result(y)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x(:)
Return Value real (size(x))
function J(x) result(y)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x(:)
Return Value real (size(x),size(x))
Call graph
test_non_linear_solvers calls vectornewton, newton, bisection, secant
vectornewton calls solve
solve calls factor_lu, solve_lu
solve_lu calls solve_u, solve_l