test – Numerical Methods
test Program
49 statements
Source File
Uses
linear_solvers
Program to show the usage of the linear_solvers module
Calls
Contents
Variables
N ti tf A b x_G x_LU x_J x_GS x_0 i u Nmax
Variables
Type Attributes Name Initial
integer, parameter :: N = 500
real :: ti
real :: tf
real :: A(N,N)
real :: b(N)
real :: x_G(N)
real :: x_LU(N)
real :: x_J(N)
real :: x_GS(N)
real :: x_0(N)
integer :: i
integer :: u
integer :: Nmax
Call graph
test calls jacobi, gauss_solve, gaussseidel, solve
gauss_solve calls make_u, solve_u
gaussseidel calls solve_l
solve calls solve_lu, factor_lu
solve_lu calls solve_l, solve_u