test_eigenvectors – Numerical Methods
test_eigenvectors Program
26 statements
Source File
Uses
eigenvectors
Program to show the usage of the the eigenvectors module.
Calls
Contents
Variables
N i A v lambda1 lambda2 lambda3 fmt
Variables
Type Attributes Name Initial
integer, parameter :: N = 3
integer :: i
real :: A(N,N)
real :: v(N)
real :: lambda1
real :: lambda2
real :: lambda3
character(len=:), allocatable :: fmt
Call graph
test_eigenvectors calls eigen_inv, eigen_max
eigen_inv calls solve_lu, factor_lu
solve_lu calls solve_u, solve_l