test_integrals – Numerical Methods
test_integrals Program
37 statements
Source File
Uses
integrals
program to show the usage of the integrals module
Calls
Variables
Type Attributes Name Initial
real, parameter :: pi = acos(-1.)
real :: a
real :: b
real :: h
real :: Int
integer :: i
Functions
function f(x) result(y)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x
Return Value real
function g(x) result(y)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x
Return Value real
Call graph
test_integrals calls quad
quad calls quad_simpson, quad_trapz