eigen_inv – Numerical Methods
eigen_inv Subroutine
32 statements
Source File
public subroutine eigen_inv(A, v, lambda, p, maxIter, err_v, v_0)
Given the matrix A, computes the eigenvector v associated to the eivenvalue lambda closer to the value p using the inverse power method.
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: A(:,:)
Symmetric matrix
real, intent(out) :: v(size(A,1))
Eigenvector
real, intent(out) :: lambda
Eigenvalue
real, intent(in) :: p
value close to the eigenvalue wanted
integer, intent(in) :: maxIter
Maximum number of iterations
real, intent(in) :: err_v
Precision for the stop criterion
real, intent(in) :: v_0(size(A,1))
Initial vector for the iteration
Calls
Called by
Contents
None
Call graph
eigen_inv calls factor_lu, solve_lu
solve_lu calls solve_u, solve_l
test_eigenvectors calls eigen_inv