factor_LU – Numerical Methods
factor_LU Subroutine
18 statements
Source File
public subroutine factor_LU(A, L, U)
Computes de LU factorization of a non-singular matrix A
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: A(:,:)
Non-singular matrix
real, intent(out) :: L(size(A,1),size(A,2))
Lower triangular matrix
real, intent(out) :: U(size(A,1),size(A,2))
Upper triangular matrix
Called by
Contents
None
Call graph
solve calls factor_lu
eigen_inv calls factor_lu
test_eigenvectors calls eigen_inv
vectornewton calls solve
test calls solve
test_non_linear_solvers calls vectornewton