solve_U – Numerical Methods
solve_U Function
11 statements
Source File
public function solve_U(U, b) result(x)
Computes the solution of an upper triangular system:
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: U(:,:)
Upper triangular matrix
real, intent(in) :: b(:)
Right hand side vector
Return Value real (size(U,2))
Solution vector x
Called by
Contents
None
Call graph
solve_lu calls solve_u
gauss_solve calls solve_u
solve calls solve_lu
test calls gauss_solve, solve
eigen_inv calls solve_lu
vectornewton calls solve
test_eigenvectors calls eigen_inv
test_non_linear_solvers calls vectornewton