solve_LU – Numerical Methods
solve_LU Function
7 statements
Source File
public function solve_LU(L, U, b) result(x)
Computes the solution to the system: where L and U are the matrices obtained from a LU factorization.
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: L(:,:)
Lower triangular matrix
real, intent(in) :: U(:,:)
Upper triangular matrix
real, intent(in) :: b(:)
Right hand side vector
Return Value real, (size(b))
Solution vector x
Calls
Called by
Call graph
solve_lu calls solve_l, solve_u
eigen_inv calls solve_lu
solve calls solve_lu
vectornewton calls solve
test_eigenvectors calls eigen_inv
test_linear_solvers calls solve
test_non_linear_solvers calls vectornewton