solve_L – Numerical Methods
solve_L Function
11 statements
Source File
public function solve_L(L, b) result(x)
Computes the solution of a lower triangular system:
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: L(:,:)
Lower triangular matrix
real, intent(in) :: b(:)
Right hand side vector
Return Value real, (size(L,2))
Solution vector x
Called by
Call graph
gaussseidel calls solve_l
solve_lu calls solve_l
eigen_inv calls solve_lu
solve calls solve_lu
test_linear_solvers calls gaussseidel, solve
vectornewton calls solve
test_eigenvectors calls eigen_inv
test_non_linear_solvers calls vectornewton