solve – Numerical Methods
solve Function
8 statements
Source File
public function solve(A, b) result(x)
Computes the solution to the system: using LU factorization.
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: A(:,:)
Non-singular matrix
real, intent(in) :: b(:)
Right hand side vector
Return Value real (size(b))
Solution vector x
Calls
Called by
Contents
None
Call graph
solve calls factor_lu, solve_lu
solve_lu calls solve_l, solve_u
vectornewton calls solve
test calls solve
test_non_linear_solvers calls vectornewton