VectorNewton – Numerical Methods
VectorNewton Function
27 statements
Source File
public function VectorNewton(f, J, x0, err_x, err_f, max_iter) result(x)
Solves the vector non-linear equation: using Newton's method.
Arguments
Type Intent Optional Attributes Name
public function f(x) result(y)
function defining the non-linear equation
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x(:)
independent variable
Return Value real (size(x))
dependent variable
public function J(x) result(y)
jacobian of function
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x(:)
independent variable
Return Value real (size(x),size(x))
dependent variable
real, intent(in) :: x0(:)
initial aproximation to the solution:
real, intent(in) :: err_x
admisible error in the solution
real, intent(in) :: err_f
admisible error in the equation
integer, intent(in) :: max_iter
maximum number of iterations
Return Value real (size(x0))
numerical aproximation to the solution
Calls
Called by
Contents
None
Call graph
vectornewton calls solve
solve calls solve_lu, factor_lu
solve_lu calls solve_l, solve_u
test_non_linear_solvers calls vectornewton